#!/bin/bash
###########################################################################
# Description:
#     This script will launch the python script of netbeez-agent
#     (forwarding any arguments passed to this script).
#
# Copyright (c) 2018-2021 Nokia, generated by srl-agent-builder
###########################################################################


_term (){
    echo "Caugth signal SIGTERM !! "
    kill -TERM "$child" 2>/dev/null
}

function main()
{
    trap _term SIGTERM

    # Fix nameserver
    sudo echo -e "nameserver 8.8.8.8\n" > /etc/resolv.conf

    # Start Docker daemon if not running
    if [[ ! -f /var/run/docker.pid ]]; then
      sudo dockerd &
    fi

    # Load container image
    sudo docker load < /netbeez_agent.tar.gz

    sudo docker volume create netbeez-config-vol1
    sudo docker-compose -f /etc/opt/srlinux/appmgr/netbeez-compose-yml up &

    local virtual_env="/opt/srlinux/python/virtual-env/bin/activate"
    local main_module="/etc/opt/srlinux/appmgr/netbeez-agent.py"

    # source the virtual-environment, which is used to ensure the correct python packages are installed,
    # and the correct python version is used
    source "${virtual_env}"
    export  PYTHONPATH="$PYTHONPATH:/etc/opt/srlinux/appmgr/:/opt/srlinux/bin:/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/sdk_protos"

    export http_proxy=""
    export https_proxy=""
    export no_proxy=""
    python3 ${main_module} &

    child=$!
    wait "$child"

}

main "$@"
