#!/bin/bash
###########################################################################
# Description:
#     This script will restart the Docker container for the Netbeez agent
#
# Copyright (c) 2018-2021 Nokia, generated by srl-agent-builder
###########################################################################

AGENT_KEY="${1}"

temp_file=$(mktemp --suffix=.yml)

_term (){
    echo "Caugth signal SIGTERM !! "
    kill -TERM "$child" 2>/dev/null
}

function write_compose()
{
cat > $temp_file << EOF
version: "2.4"
services:
  nb-agent:
    image: netbeez/nb-agent
    network_mode: "host"
    dns:
      - "8.8.8.8" # Google DNS
      - "8.8.4.4" # Google DNS2
    container_name: nb-agent
    environment:
      - "INTERFACES=mgmt0.0"
      - "AGENT_UUID=7025285876ba48abb2be49ab0f8b9bbe"
      - "NB_SECRET_KEY=${AGENT_KEY}"
    volumes:
      - netbeez-config-vol:/etc/netbeez/persistence/:rw
volumes:
  netbeez-config-vol:
EOF
}

function main()
{
    trap _term SIGTERM

    # Start Docker daemon if not running
    if [[ ! -f /var/run/docker.pid ]]; then
      sudo dockerd &
    fi

    # Load container image
    sudo docker load < /netbeez_agent.tar.gz

    sudo docker volume create netbeez-config-vol1

    write_compose
    sudo docker-compose -f $temp_file up &
}

main "$@"
